name: whitelabel
description: A white label sample project

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter_dotenv: ^5.0.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # accessing the runtime config values from JSON - assets/file/network
  global_configuration: ^2.0.0-nullsafety.1
  fluttertoast: 
  # for making the ThemeData from the constructed JSON
  # json_theme: ^3.3.1-pre113+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/fonts
    - assets/cfg/
    - assets/config/
    # - fonts/


  
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
        - asset: fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700

